### ISSUE TITLE
Unable to run/pass e2e-tests

### ISSUE THREAD

**Issue by prolificcoder** [appium/appium-ios-driver#105]
I am trying to run e2e-test on my El cap machine, which has appium-doctor passing

My error and setup is in this gist https://gist.github.com/prolificcoder/a7e76e4ea26d56b462f0 

Am I doing something wrong?

**Comment by prolificcoder** [comment]
uicatalog - load zipped app via url @skip-real-device
    94) "before all" hook: callee$1$0


  4 passing (2h)
  1 pending
  94 failing

Also they took a long time to fail

**Comment by imurchie** [comment]
Looking into it.

**Comment by imurchie** [comment]
In the meantime, could you try running at least one of the tests with `_FORCE_LOGS=1` on? This will give the full logs, which would be very helpful to diagnose.

**Comment by prolificcoder** [comment]
I am just running this and seeing these coming in
```shell
dbug Instruments And launch timeouts (in ms): {"global":60000,"afterSimLaunch":10000}
dbug Instruments [INST STDERR] Instruments Usage Error : Ambiguous device name/identifier 'iPhone 6 (9.2) [':
dbug Instruments iPhone 6 (9.2) [C7AAD73C-E9D7-4556-975C-61294707C6AE]
dbug Instruments iPhone 6 (9.2) [305EF0DD-CD40-4D17-AEED-3AA14E26F167]
dbug Instruments Instruments exited with code 255
ERR! Instruments Error launching instruments: Instruments crashed on startup
dbug iOSSim Killing all iOS Simulators
dbug Instruments Attempting to launch instruments, this is try #5
info Instruments Launching instruments
dbug Instruments Attempting to run app on iPhone 6 (9.2) [
info Instruments On xcode 7.0+, instruments-without-delay does not work, skipping instruments-without-delay
dbug Instruments Found Insruments-Without-Delay: /Users/malugus/Code/appium-ios-driver/node_modules/appium-instruments/thirdparty/iwd7
dbug Instruments Spawning instruments with command: '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /var/folders/hr/fs08w8hn63j9d4m3tlxd3bqc0000gn/T/appium-instruments/instrumentscli0.trace -w "iPhone 6 (9.2) [" /var/folders/hr/fs08w8hn63j9d4m3tlxd3bqc0000gn/T/2016129-91020-1xym23p/TestApp/build/Release-iphonesimulator/TestApp.app -e UIASCRIPT "/Users/malugus/Library/Application Support/appium/bootstrap/bootstrap-665a1c83dceb9654.js" -e UIARESULTSPATH /var/folders/hr/fs08w8hn63j9d4m3tlxd3bqc0000gn/T/appium-instruments'
dbug Instruments And launch timeouts (in ms): {"global":60000,"afterSimLaunch":10000}
dbug Instruments [INST STDERR] Instruments Usage Error : Ambiguous device name/identifier 'iPhone 6 (9.2) [':
dbug Instruments iPhone 6 (9.2) [C7AAD73C-E9D7-4556-975C-61294707C6AE]
dbug Instruments iPhone 6 (9.2) [305EF0DD-CD40-4D17-AEED-3AA14E26F167]
dbug Instruments Instruments exited with code 255
ERR! Instruments Error launching instruments: Instruments crashed on startup
ERR! Instruments Error: We exceeded the number of retries allowed for instruments to successfully start; failing launch
ERR! Instruments     at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
ERR! Instruments     at Instruments.launch$ (lib/instruments.js:210:15)
ERR! Instruments     at tryCatch (/Users/malugus/Code/appium-ios-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
ERR! Instruments     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/malugus/Code/appium-ios-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
ERR! Instruments     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/malugus/Code/appium-ios-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
ERR! Instruments     at GeneratorFunctionPrototype.invoke (/Users/malugus/Code/appium-ios-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
ERR! Instruments     at bound (domain.js:287:14)
ERR! Instruments     at GeneratorFunctionPrototype.runBound (domain.js:300:12)
ERR! Instruments     at run (/Users/malugus/Code/appium-ios-driver/node_modules/core-js/library/modules/es6.promise.js:104:47)
ERR! Instruments     at /Users/malugus/Code/appium-ios-driver/node_modules/core-js/library/modules/es6.promise.js:115:28
ERR! Instruments     at flush (/Users/malugus/Code/appium-ios-driver/node_modules/core-js/library/modules/$.microtask.js:19:5)
ERR! Instruments     at nextTickCallbackWith0Args (node.js:453:9)
ERR! Instruments     at process._tickDomainCallback (node.js:423:13)
ERR! Instruments  [Error: We exceeded the number of retries allowed for instruments to successfully start; failing launch]
```

**Comment by imurchie** [comment]
Ok. This means that you have two `iPhone 6` simulators in iOS 9.2. Instruments doesn't know how to distinguish them, unfortunately. 

Can you delete one of the two?

**Comment by prolificcoder** [comment]
Yeah that did the trick I guess but still this took a lot of time and 43 tests failed

  173 passing (1h)
  3 pending
  48 failing

Is this expected? 

All the error has this message

```shell
testapp - timeout zero timeout "before all" hook: callee$1$0:
     Error: The desired capabilities must include either an app or a bundleId for iOS
      at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
      at IosDriver.validateDesiredCaps (lib/driver.js:383:14)
      at IosDriver.callee$0$0$ (lib/commands/session.js:13:8)
      at tryCatch (node_modules/babel-runtime/regenerator/runtime.js:67:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/babel-runtime/regenerator/runtime.js:315:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/babel-runtime/regenerator/runtime.js:100:21)
      at invoke (node_modules/babel-runtime/regenerator/runtime.js:136:37)
      at bound (domain.js:287:14)
      at runBound (domain.js:300:12)
      at enqueueResult (node_modules/babel-runtime/regenerator/runtime.js:185:17)
      at new Promise (node_modules/core-js/library/modules/es6.promise.js:197:7)
      at AsyncIterator.enqueue (node_modules/babel-runtime/regenerator/runtime.js:184:12)
      at AsyncIterator.prototype.(anonymous function) [as next] (node_modules/babel-runtime/regenerator/runtime.js:100:21)
      at Object.runtime.async (node_modules/babel-runtime/regenerator/runtime.js:209:12)
      at IosDriver.callee$0$0 [as createSession] (lib/commands/session.js:8:46)
      at IosDriver.createSession$ (lib/driver.js:41:16)```

**Comment by prolificcoder** [comment]
I think a failure retries few times, so that contributes to the time taken.

**Comment by imurchie** [comment]
Can you provide the output from running one of these tests with `_FORCE_LOGS=1` on?
